version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'example.com -> http://django:8080'
      STAGE: 'local' # or 'production'
    # volumes:
    #   - /data/ssl_certs:/var/lib/https-portal

  django:
    build: ./django-uwsgi-nginx
    ports:
      - '8080'
